#!/usr/bin/env ruby

$LOAD_PATH.unshift(File.join(File.expand_path(File.dirname(__FILE__)), 'lib'))
require 'bundler'
Bundler.require # removes need for 'bundle exec'

require 'twitter_auth'
require 'twitter'

$stdout.sync = true

begin
  object_count = Integer(ARGV[0])
rescue ArgumentError, TypeError
  object_count = 8
end

client = Twitter::Streaming::Client.new() do |config|
  twauth                     = TwitterAuth.new
  config.consumer_key        = twauth.consumer_key
  config.consumer_secret     = twauth.consumer_secret
  config.access_token        = twauth.access_token
  config.access_token_secret = twauth.access_token_secret
end

client.sample do |data|
  $stdout.puts(data.to_h)
end

